#Created by Tania Sanchez (2014-2016) tania.sanchezmonroy@manchester.ac.uk
#This code is used to delete the auxiliary files generated by ABAQUS

listBack=['.com','.dat','.ipm','.lck','.log','.msg','.prt','.sta', '.sim', '.stt', '.mdl']
for i in listBack:
	if os.path.exists(wDr+'/'+jobName+i)==True:
		os.remove(wDr+'/'+jobName+i)
	